###############################################
# Principal Component Analysis (PCA) Plotting
###############################################

# Load required libraries

library(ggplot2)
library(tidyverse)
library(RColorBrewer)
library(openxlsx)
library(readxl)

# Set working directory to output folder
setwd("C:/Users/USUARIO/Desktop/paper/Analysis-result/Population structure/PCA/generalist")
getwd() # Confirm working directory

# Load PCA eigenvector file generated by SmartPCA
evecDat <- read.table("yali.pca.evec", skip = 1,
                      col.names = c("Sample", "PC1", "PC2", "PC3", "PC4", "PC5",
                                    "PC6", "PC7", "PC8", "PC9", "PC10", "Pop")) 
# 'Pop' corresponds to group assignment column generated by SmartPCA

# Load metadata to annotate PCA points (e.g., geography, habitat, clade)
metadata <- read_excel("update_manfinetreeposition.xlsx")

# Match PCA samples with metadata
samples_pca <- evecDat$Sample
metadata_filtered <- subset(metadata, metadata$treesamp %in% samples_pca)

# Sort both datasets by sample ID to align rows
evecDat <- evecDat[order(evecDat$Sample), ]
metadata_filtered <- metadata_filtered[order(metadata_filtered$treesamp), ]

# Annotate PCA dataframe with metadata
evecDat$geo         <- metadata_filtered$geo
evecDat$eco         <- metadata_filtered$habitat
evecDat$natvsanth   <- metadata_filtered$natvsan
evecDat$geno        <- as.factor(metadata_filtered$bigeyclades)
evecDat$linajes     <- maypop$k14      # You must define `maypop` beforehand
evecDat$k7          <- maypop$k7       # Same for this variable
evecDat$finepop     <- metadata_filtered$FinePop2

# Define custom color palettes
color_habitat <- c(
  host     = "#ff3131",
  food     = "#62abe2",
  soil     = "#c85700",
  industry = "#505050",
  marine   = "#024cae"
)

color_region <- c(
  Africa          = "red",
  America         = "gold",
  Asia            = "green",
  Europe          = "blue",
  Oceania         = "black",
  `Southern Ocean` = "cyan",
  Unknown         = "white"
)

my_colors_pop <- c("Eur1" = "#F29E6D", "Eur2" = "#05A6A6", "So-HC" = "#03738C", 
                   "NoAm" = "#F23E2E", "W29 clade" = "#152B59", "Hyp" = "grey")

# Create PCA scatter plot using ggplot2
# Create PCA scatter plot with customized aesthetics
library(ggrepel)
p1 <- evecDat %>%
  # To exclude putative mosaic strains, uncomment the line below
  # filter(!Sample %in% c(1991, 841)) %>%
  ggplot(aes(x = PC1, y = PC2, color = finepop)) +
  geom_point(size = 2.5, stroke = 0.5) +  # black-edged, white-filled points
  scale_color_manual(values = my_colors_pop) +
  # geom_text_repel(aes(label = Sample), size = 3, max.overlaps = Inf)+
  labs(
    x = "PC1 (2.99%)",
    y = "PC2 (2.33%)",
    color = "Population"
  ) +
  theme(
    panel.background = element_rect(fill = "white", color = NA),
    panel.border = element_rect(color = "black", fill = NA, linewidth = 1),
    panel.grid.major = element_blank(),
    panel.grid.minor = element_blank(),
    axis.line = element_line(color = "black"),
    axis.ticks = element_line(color = "black"),
    plot.title = element_text(hjust = 0.5, face = "bold", size = 20),
    axis.title = element_text(face = "bold", size = 16),
    axis.text = element_text(size = 14),
    legend.title = element_text(face = "bold", size = 14),
    legend.text = element_text(size = 12),
    legend.position = "right"
  )

# Display the plot
print(p1)
# Save the plot as high-resolution JPG
ggsave("20241028_PCAWhole_lin.jpg",
       plot   = p1,
       device = "jpg",
       dpi    = 300,
       width  = 8,
       height = 6,
       units  = "in")
